### ISSUE TITLE
addon.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by xiaoge136** [AtiqGauri/Nodejs-Napi-Addon-Using-Cmake#4]
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "D:\Nodejs-Napi-Addon-Using-Cmake\build"
info CMD CONFIGURE
info RUN cmake "D:\Nodejs-Napi-Addon-Using-Cmake" --no-warn-unused-cli -G"Visual Studio 15" -DCMAKE_JS_VERSION="6.1.0" -
DCMAKE_BUILD_TYPE="Release" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="D:\Nodejs-Napi-Addon-Using-Cmake\build" -DCMAKE_JS_INC="C:
\Users\XX\.cmake-js\node-ia32\v14.15.5\include\node" -DCMAKE_JS_SRC="D:/Nodejs-Napi-Addon-Using-Cmake/node_mo
dules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="14.15.5" -DNODE_ARCH="ia32"
-DCMAKE_JS_LIB="C:\Users\XX\.cmake-js\node-ia32\v14.15.5\win-x86\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELA
YLOAD:NODE.EXE /SAFESEH:NO" -Djs_arch="ia32"
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.2702
3/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Nodejs-Napi-Addon-Using-Cmake/build
info CMD BUILD
info RUN cmake --build "D:\Nodejs-Napi-Addon-Using-Cmake\build" --config Release
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule D:/Nodejs-Napi-Addon-Using-Cmake/CMakeLists.txt
  example.cpp
  win_delay_load_hook.cc
  正在生成代码...
    正在创建库 D:/Nodejs-Napi-Addon-Using-Cmake/build/Release/addon.lib 和对象 D:/Nodejs-Napi-Addon-Using-Cmake/build/Re
lease/a
  ddon.exp
  addon.vcxproj -> D:\Nodejs-Napi-Addon-Using-Cmake\build\Release\addon.node
  Building Custom Rule D:/Nodejs-Napi-Addon-Using-Cmake/CMakeLists.txt
audited 139 packages in 12.073s

2 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

XX@HIH-D-17633 MINGW64 /d/Nodejs-Napi-Addon-Using-Cmake (master)
$ npm start

> test@1.0.0 start D:\Nodejs-Napi-Addon-Using-Cmake
> node index.js

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\Nodejs-Napi-Addon-Using-Cmake\build\Release\addon.node is not a valid Win32 application.
\\?\D:\Nodejs-Napi-Addon-Using-Cmake\build\Release\addon.node
[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (D:\Nodejs-Napi-Addon-Using-Cmake\index.js:1:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XX\AppData\Roaming\npm-cache\_logs\2021-05-25T05_27_48_788Z-debug.log

**Comment by AtiqGauri** [comment]
There is something wrong with your node version...
what machine are you using, is there any WSL or something like that installed
